from __future__ import annotations

from pathlib import Path

APP_NAME = "Harness Admin"
APP_VERSION = "0.1.0"
TASK_NAME = "HarnessRemoteApprovalWatcher"
DEFAULT_RUNTIME_HOME_NAME = ".harness-runtime"

CHANNEL_MODE_TELEGRAM_ONLY = "telegram-only"
CHANNEL_MODE_TELEGRAM_AND_NTFY = "telegram-and-ntfy"
CHANNEL_MODE_CHOICES = (
    CHANNEL_MODE_TELEGRAM_ONLY,
    CHANNEL_MODE_TELEGRAM_AND_NTFY,
)

DEFAULT_GRACE_MINUTES = 10
DEFAULT_NTFY_SERVER = "https://ntfy.sh"
DEFAULT_NOTIFICATION_CHANNEL_MODE = CHANNEL_MODE_TELEGRAM_ONLY
DEFAULT_AWAY_MINUTES = 120

ENV_TELEGRAM_BOT_TOKEN = "HARNESS_TELEGRAM_BOT_TOKEN"
ENV_TELEGRAM_CHAT_ID = "HARNESS_TELEGRAM_CHAT_ID"
ENV_NTFY_SERVER = "HARNESS_NTFY_SERVER"
ENV_NTFY_TOPIC = "HARNESS_NTFY_TOPIC"
ENV_LOCAL_RESPONSE_GRACE_MINUTES = "HARNESS_LOCAL_RESPONSE_GRACE_MINUTES"
ENV_RUNTIME_HOME = "HARNESS_RUNTIME_HOME"
ENV_NOTIFICATION_CHANNEL_MODE = "HARNESS_NOTIFICATION_CHANNEL_MODE"

ENV_KEYS = (
    ENV_TELEGRAM_BOT_TOKEN,
    ENV_TELEGRAM_CHAT_ID,
    ENV_NTFY_SERVER,
    ENV_NTFY_TOPIC,
    ENV_LOCAL_RESPONSE_GRACE_MINUTES,
    ENV_RUNTIME_HOME,
    ENV_NOTIFICATION_CHANNEL_MODE,
)

REQUIRED_REPO_MARKERS = (
    Path(".agents/scripts/open_user_gate.ps1"),
    Path(".agents/scripts/invoke_user_gate.ps1"),
)

OPTIONAL_REPO_MARKERS = (
    Path(".agents/runtime/approvals"),
)

BOTFATHER_URL = "https://t.me/BotFather"
TELEGRAM_WEB_URL = "https://web.telegram.org/"
NTFY_WEB_URL = "https://ntfy.sh/"

LOG_FILE_NAME = "harness_admin.log"
WATCHER_SUMMARY_FILE_NAME = "watcher_last_summary.json"
